src/Entity/Posts.php
<?php

namespace App\Entity;

use App\Entity\User;
use App\Repository\PostsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Length;

#[ORM\Entity(repositoryClass: PostsRepository::class)]
class Posts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $posts_picture;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $posts_place;

    #[ORM\Column(type: 'text', nullable: true), Length(min: 5)]
    private $posts_describe;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class, orphanRemoval: true)]
    private $comments;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: CommentPost::class)]
    private $commentPosts;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: PostLike::class)]
    private $likes;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->commentPosts = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->posts_describe;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPostsPicture(): ?string
    {
        return $this->posts_picture;
    }

    public function setPostsPicture(string $posts_picture): self
    {
        $this->posts_picture = $posts_picture;

        return $this;
    }

    public function getPostsPlace(): ?string
    {
        return $this->posts_place;
    }

    public function setPostsPlace(?string $posts_place): self
    {

        $this->posts_place = $posts_place;

        return $this;
    }

    public function getPostsDescribe(): ?string
    {
        return $this->posts_describe;
    }

    public function setPostsDescribe(?string $posts_describe): self
    {
        $this->posts_describe = $posts_describe;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CommentPost>
     */
    public function getCommentPosts(): Collection
    {
        return $this->commentPosts;
    }

    public function addCommentPost(CommentPost $commentPost): self
    {
        if (!$this->commentPosts->contains($commentPost)) {
            $this->commentPosts[] = $commentPost;
            $commentPost->setPost($this);
        }

        return $this;
    }

    public function removeCommentPost(CommentPost $commentPost): self
    {
        if ($this->commentPosts->removeElement($commentPost)) {
            // set the owning side to null (unless already changed)
            if ($commentPost->getPost() === $this) {
                $commentPost->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PostLike>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(PostLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setPost($this);
        }

        return $this;
    }

    public function removeLike(PostLike $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getPost() === $this) {
                $like->setPost(null);
            }
        }

        return $this;
    }

    /**
     * posts liked by user
     */
    public function isLikedByUser(User $user) : bool
    {
        foreach($this->likes as $like){
            if($like->getUser() === $user){
                return true;
            }
        }
        return false;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
/**
 * @UniqueEntity(
 *     fields={"email"},
 *     message="L'email existe déjà"
 * )
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $name;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $surname;

    #[ORM\Column(type: 'string', length: 255)]
    private $pseudo;

    #[ORM\Column(type: 'string', length: 255)]
    /**
     * @Assert\Email(groups={"registration"})
     */
    private $email;

    #[ORM\Column(type: 'string', length: 255)]
    /**
     * @Assert\Length(
     *      min = 6,
     *      minMessage = "Le mot de passe doit faire {{ limit }} charactères minimum",
     *
     * )
     * @Assert\EqualTo(
     *     propertyPath="confirm_password",
     *     message="Votre mot de passe doit être identique",
     *     groups={"registration"}
     *     )
     */
    private $password;

    /**
     * @Assert\EqualTo(
     *     propertyPath="password",
     *     message="Le mot de passe doit être identique",
     *     groups={"registration"}
     *     )
     */
    public $confirm_password;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $biography;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Posts::class, orphanRemoval: true)]
    private $posts;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $profile_picture;

    #[ORM\Column(type: 'json', nullable: true)]
    private $roles = [];

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class)]
    private $comments;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: CommentPost::class)]
    private $commentPosts;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: PostLike::class)]
    private $likes;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->commentPosts = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(?string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(?string $biography): self
    {
        $this->biography = $biography;

        return $this;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getSalt(){

    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';
 
        return array_unique($roles);
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @return Collection<int, Posts>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Posts $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Posts $post): self
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfilePicture(?string $profile_picture): self
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    public function setRoles(?array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CommentPost>
     */
    public function getCommentPosts(): Collection
    {
        return $this->commentPosts;
    }

    public function addCommentPost(CommentPost $commentPost): self
    {
        if (!$this->commentPosts->contains($commentPost)) {
            $this->commentPosts[] = $commentPost;
            $commentPost->setUser($this);
        }

        return $this;
    }

    public function removeCommentPost(CommentPost $commentPost): self
    {
        if ($this->commentPosts->removeElement($commentPost)) {
            // set the owning side to null (unless already changed)
            if ($commentPost->getUser() === $this) {
                $commentPost->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PostLike>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(PostLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(PostLike $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getUser() === $this) {
                $like->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\PostsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use App\Entity\CommentPost;
use App\Form\CommentPostType;
use App\Repository\CommentPostRepository;


class HomeController extends AbstractController
{
    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    #[Route('/', name: 'app_home', methods: ['GET', 'POST'])]
    public function index(Request $request, CommentPostRepository $commentPostRepository ,PostsRepository $postsRepository): Response
    {
        $user = $this->security->getUser();

       $comment = new CommentPost();
       $form = $this->createForm(CommentPostType::class, $comment);
       $form->handleRequest($request);
           if ($form->isSubmitted() && $form->isValid()) {
               echo("ok");
           }


        return $this->render('home/index.html.twig', [
            'user' => $user,
            'posts' => $postsRepository->findBy(array(), array('createdAt' => 'DESC')),
            'comment_form_post' => $form->createView(),
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CloneInsta{% endblock %}
{% block stylesheets %}<link href="{{ asset('styles/css/home.css') }}" rel="stylesheet"/>{% endblock %}

{% block body %}
<div class="wrap" id="home_container">
    <div id="actu_container">
        {% if posts is empty %}
        <article id="post_actu">
                <div class="post_header">
                    <p>CloneInsta</p>
                </div>
                <div id="post_description">
                    <p>Il n'y a aucun post à afficher pour le moment ...</p>
                </div>
            </article>
        {% endif %}


        {% for post in posts %}
            <article id="post_actu">
                <div class="post_header">
                    <div class="left_header">
                        {% if post.user.profilePicture is empty %}
                            <a href="{{ path('app_profile_show', {'id': post.user.id}) }}"><img class="profil_user" src="/img/default_user.png" alt="photo de profil"></a>
                        {% else %}
                            <a href="{{ path('app_profile_show', {'id': post.user.id}) }}"><img class="profil_user" src="{{ asset('/uploads/' ~ post.user.profilePicture ) | imagine_filter('minProfilePicture') }}" alt="Photo de profil"></a>
                        {% endif %}
                            <div class="post_info">
                            <a href="{{ path('app_profile_show', {'id': post.user.id}) }}"><h3>{{ post.user.pseudo }}</h3></a>
                            <p>{{ post.postsPlace }}</p>
                        </div>
                    </div>

                    <div class="right_header">
                        <a href=""><i class="fa-solid fa-ellipsis"></i></a>
                    </div>
                </div>

                <div id="post_picture">
                    <img class="profil_user" src="{{ asset('/uploads/' ~ post.postsPicture ) | imagine_filter('actuPicture') }}" alt="photo du post">
                </div>

                <div id="post_description">
                    <p><a href="{{ path('app_profile_show', {'id': post.user.id}) }}">{{ post.user.pseudo }}</a> {{ post.postsDescribe }}</p>
                </div>

                <div class="community_container">
                    <a href="{{ path('post_like', {'id': post.id}) }}" class="btn btn-link js-like-link">
                        {% if app.user and post.isLikedByUser(app.user) %}
                            <i class="fa-solid fa-heart"></i>
                        {% else %}
                            <i class="fa-regular fa-heart"></i>
                        {% endif %}
                        <span class="js-likes">{{ post.likes | length }}</span>
                    </a>
                </div>

                {# <div id="post_comment_form">
                   {{ form(comment_form_post) }}
                </div> #}

            </article>
        {% endfor %}
    </div>

    <div id="footer_container">
        {% if user is empty%}
            <p>&copy; 2022 INSTACLONE par Pinto Sanhudo Jody</p>
        {% else %}
            <div class="footer_profile">
                <div class="footer_profile_items">
                {% if user.profilePicture is empty %}
                    <img class="profil_user" src="/img/default_user.png" alt="photo de profil">
                {% else %}
                    <img class="footer_profil_user" src="{{ asset('/uploads/' ~ user.profilePicture ) | imagine_filter('minProfilePicture') }}" alt="Photo de profil">
                {% endif %}
                    <div class="footer_profile_info">
                        <h4>{{ user.pseudo }}</h4>
                        <p>{{ user.surname }} {{ user.name }}</p>
                    </div>
                </div>
                
                <div>
                    <a href="{{ path('app_profile') }}">Profil</a>
                </div>
            </div>
            <p>&copy; 2022 INSTACLONE par Pinto Sanhudo Jody</p>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block javascripts %}
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="{{ asset('js/like.js') }}"></script>
{% endblock %}